### ISSUE TITLE
Dataset doubt

### ISSUE THREAD

**Issue by scmanjarrez** [nikk-nikaznan/SCU#1]
Hi, I've read your paper and found this repository. I was trying to understand the dataset shape and came with a doubt... is that a real dataset? Or just generated data? All numbers look pretty similar... all of them are in the range 0.32-0.34, which seems weird given that eeg signals usually fluctuate a lot. Also, are dataset values in volts? or microvolts?
Thanks

**Comment by nikk-nikaznan** [comment]
Hi, Sorry about the confusion. The sample dataset is not real data, it is there as an example on how to load the data on regards to the data shape. We are not publishing the real data yet.

**Comment by scmanjarrez** [comment]
Oh, that makes sense, thank you!
